USE customer_behavior;
select * from customer limit 20;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM customer
GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount FROM customer
WHERE discount_applied = 'yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT * FROM customer LIMIT 5;
SELECT item_purchased, ROUND(AVG(review_rating), 2) FROM customer
GROUP BY item_purchased
order by AVG(review_rating) DESC
LIMIT 5; 
