USE customer_behavior;
select * from customer limit 20;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM customer
GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount FROM customer
WHERE discount_applied = 'yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Stardard and Express Shipping
SELECT AVG(purchase_amount), shipping_type FROM customer
WHERE shipping_type IN("Express", "Standard")
GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend total revenue between subscribers and non-subscribers.
SELECT COUNT(customer_id) AS No_Customers, SUM(purchase_amount), AVG(purchase_amount), subscription_status FROM customer
GROUP BY subscription_status;
-- Q6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT * FROM customer LIMIT 5;
SELECT item_purchased,
	ROUND((discount_count * 100.0 / total_count), 2) AS Percentage
FROM (SELECT item_purchased, SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_count,
		COUNT(*) AS total_count FROM customer
		GROUP BY item_purchased) t
ORDER BY Percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning and Loyal based on their total
-- number of previous purchases and show the count of each segment
SELECT MIN(previous_purchases), MAX(previous_purchases), AVG(previous_purchases) FROM customer;
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases <= 5 THEN "New"
    WHEN previous_purchases BETWEEN 5 AND 25 THEN "Returning"
    ELSE  "Loyal"
END AS customer_segment 
FROM customer)
SELECT customer_segment, COUNT(*) AS "Number_of_Customers" FROM customer_type
GROUP BY customer_segment;
